In [1]:
import glob
import pandas as pd
import json
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import datetime

In [2]:
outlet_ratings=pd.read_csv('60 outlets ratings by factcheckers.csv')
outlet_ratings.columns=['domain','score','type','twitter_handle']
outlet_ratings['score']=(outlet_ratings['score']-1)/4.
Domains=set(outlet_ratings['domain'])

In [3]:
outlet_ratings['score'].min(),outlet_ratings['score'].max()

(0.0, 0.9285714285)

In [74]:
with open('data/twitter_data/tweeted_domains.csv','w') as outfile:
    outfile.write('screen_name,domain,date,RT,site\n')
    for i,filename in enumerate(glob.glob('/Users/mm1049/Dropbox/Personal/Research/crt-estimator/data/data_merged_20211114/combined_till_20211112_processed/*.txt')):
            try:
                data = json.load(open(filename))
                screen_name = filename.split('/')[-1].replace(".txt","")
                if 'RTs' not in data.keys():
                    data['RTs']=[0]*len(data['sites'])
                for site,date,RT in zip(data['sites'],data['dates'],data['RTs']):
                    domain=''
                    for domain_ in Domains:
                        if site.find(domain_)!=-1:
                            domain=domain_
                    outfile.write('{},{},{},{},{}\n'.format(screen_name,domain,date,RT,site.replace(',','')))


            except Exception as e:
                print (e)
                print ('screen_name',screen_name)

In [4]:
tweeted_domains=pd.read_csv('data/twitter_data/tweeted_domains.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'tweeted_domains.csv'

In [76]:
tweeted_domains

,screen_name,domain,date,RT,site
0,manuelafonseca,NaN,2017-07-05 19:41:47,0,NaN
1,manuelafonseca,NaN,2014-06-11 16:06:05,0,http://seer.ufrgs.br/index.php/EmQuestao/artic...
2,manuelafonseca,NaN,2014-01-18 21:46:03,0,http://revistapesquisa.fapesp.br/2013/05/14/os...
3,manuelafonseca,NaN,2013-06-24 18:57:04,0,http://hivereader.com/
4,manuelafonseca,NaN,2013-06-07 13:06:45,1,NaN
...,...,...,...,...,...
2844893,mkokc,NaN,2020-11-12 19:21:58,0,NaN
2844894,mkokc,NaN,2020-11-12 19:18:18,0,NaN
2844895,mkokc,NaN,2020-11-12 18:10:26,0,NaN
2844896,mkokc,NaN,2020-11-12 18:08:35,0,NaN
2844897,mkokc,NaN,2020-11-12 13:29:27,0,https://twitter.com/mkokc/status/1326879785021...

In [77]:
df=tweeted_domains
df=pd.merge(left=df,right=outlet_ratings,on='domain',how='left')

In [78]:
df_=df.groupby('screen_name').sum().reset_index()
df_=df_[['screen_name','score']]
df_.columns=['screen_name','outlet_score']
df_.to_csv('data/twitter_data/outlet_scores_sum.csv',index=False)

In [79]:
df_=df.groupby('screen_name').mean().reset_index()
df_=df_[['screen_name','score']]
df_.columns=['screen_name','outlet_score']
df_.to_csv('data/twitter_data/outlet_scores_mean.csv',index=False)

In [80]:
df_

          screen_name  outlet_score
0          11Brianope      0.692857
1     11InningStretch      0.410714
2           1711emmar           NaN
3         176Abdullah           NaN
4              19KO77           NaN
...               ...           ...
1700             yuhj           NaN
1701  yyesidolikecake      0.757353
1702          zalisis           NaN
1703      zemuogele83      0.807143
1704        zx_chrome           NaN

[1705 rows x 2 columns]